# Kubernetes deployment configuration for Planning Poker with MySQL
# This example shows how to deploy with an external MySQL database

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: planning-poker-config-mysql
  namespace: default
data:
  DATABASE_TYPE: "mysql"
  DATABASE_HOST: "mysql-service"
  DATABASE_PORT: "3306"
  DATABASE_NAME: "planning_poker"
  DATABASE_USER: "planning_poker_user"
  DATABASE_CHARSET: "utf8mb4"
  FLASK_DEBUG: "false"

---
apiVersion: v1
kind: Secret
metadata:
  name: planning-poker-secrets-mysql
  namespace: default
type: Opaque
stringData:
  DATABASE_PASSWORD: "your-secure-password-here"
  SECRET_KEY: "your-flask-secret-key-here"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: planning-poker-mysql
  namespace: default
  labels:
    app: planning-poker-mysql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: planning-poker-mysql
  template:
    metadata:
      labels:
        app: planning-poker-mysql
    spec:
      containers:
      - name: planning-poker
        image: your-registry/planning-poker:latest
        ports:
        - containerPort: 8000
          name: http
        envFrom:
        - configMapRef:
            name: planning-poker-config-mysql
        env:
        - name: DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: planning-poker-secrets-mysql
              key: DATABASE_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: planning-poker-secrets-mysql
              key: SECRET_KEY
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - python
            - /app/healthcheck.py
            - full
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          exec:
            command:
            - python
            - /app/healthcheck.py
            - app
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

---
apiVersion: v1
kind: Service
metadata:
  name: planning-poker-mysql-service
  namespace: default
  labels:
    app: planning-poker-mysql
spec:
  selector:
    app: planning-poker-mysql
  ports:
  - name: http
    port: 80
    targetPort: 8000
    protocol: TCP
  type: ClusterIP
